<a href="https://colab.research.google.com/github/mallika01bug/PyTorch-Notes/blob/main/MyPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [1]:
!pip list

Package                                  Version
---------------------------------------- ------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.3
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                          

**Tensors (Collection of homogeneous type of data)**


---


1. Tensor is a collection of same type of multidimentional matrix

2. Similar to NumPy array but more powerfull to work on GPUs rather than CPUs
3. Its default datatype is float32
4. it is more suitable for deep learning, GenAI and Agentic AI    than Numpy array
5. allows negative as well as positive indexing

In [2]:
import torch as tr
import numpy as np

Let's see the comparision between List , Numpy array and Tensors

**List**

In [3]:
a1=[1,56,23,78]
a2=[2,"abc",78,34,67]
a3=[[23,4],[45,67]]
print(a1)
print(a2)
print(a3)

[1, 56, 23, 78]
[2, 'abc', 78, 34, 67]
[[23, 4], [45, 67]]


In [4]:
a1[2]

23

In [5]:
a3[0][1]

4

**Numpy Array**

In [6]:
n1=np.array([1,56,23,89])
n1.dtype

dtype('int64')

In [7]:
n2=np.array([[1,2.8,3],[4,5,6]])
n2

array([[1. , 2.8, 3. ],
       [4. , 5. , 6. ]])

In [8]:
n3=np.random.randint(3,16,size=(4,5))
n3

array([[ 4, 12,  4, 11,  8],
       [12, 10, 10,  9,  3],
       [15, 14, 10, 10, 13],
       [11,  7, 14, 14,  7]])

In [9]:
n1[0:3]

array([ 1, 56, 23])

In [10]:
n3[0:2,1:3]

array([[12,  4],
       [10, 10]])

**Tensors**

In [12]:
t1=tr.tensor([2,6,3,8,5])
t1

tensor([2, 6, 3, 8, 5])

In [13]:
t1[0]

tensor(2)

In [14]:
t1[-2]

tensor(8)

In [15]:
t2=tr.tensor([[1,2,3],[3,4,5]])
t2

tensor([[1, 2, 3],
        [3, 4, 5]])

In [17]:
t2[0][0:2]

tensor([1, 2])

In [20]:
t4=tr.tensor(np.arange(5))
t4

tensor([0, 1, 2, 3, 4])

In [21]:
t4.dtype

torch.int64

**Tensor is mutable**

In [22]:
t1

tensor([2, 6, 3, 8, 5])

In [23]:
t1[0]=100
t1

tensor([100,   6,   3,   8,   5])

checkout shape and slicing in tensors which is same aa numpy as well as list

In [24]:
t1=tr.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
t1.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
t1.reshape(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
t1.reshape(-1,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
t1.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Slicing**

In [32]:
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
t1[0:5:2]

tensor([0, 2, 4])

In [35]:
t1[::3]

tensor([0, 3, 6, 9])

In [40]:
t2=t1.reshape(5,-1)
t2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [42]:
t2[0:4,1]

tensor([1, 3, 5, 7])

In [43]:
t2[0:4,1:]

tensor([[1],
        [3],
        [5],
        [7]])